apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: marketplace
spec:
  selector:
    app: kafka
  ports:
    - name: plaintext
      port: 9092
      targetPort: 9092
    - name: plaintext-internal
      port: 9093
      targetPort: 9093
  type: ClusterIP
